### ISSUE TITLE
Stockpiles can be hopper emptied.

### ISSUE THREAD

**Issue by Konfusioned** [Clickism/ClickShop#1]
If a hopper is placed below a stockpile, it will empty out the stockpile.  Naturally, they can be hidden away; however, the same trick won't work for the main shop, so it might be worth fixing the stockpiles as well.

I did manage to "protect" a stockpile by surrounding it with other stockpiles.

**Comment by Clickism** [comment]
Fixed in the rewrite. Hoppers can't be placed under stockpiles, it might still however be possible to use hopper minecarts.
