### ISSUE TITLE
Can the plug-in be updated so that I can customize the language files?

### ISSUE THREAD

**Issue by Usasi103** [Clickism/ClickShop#3]
plsI! ! ! am modifying the config file!! Because English is not my native language!

**Comment by Clickism** [comment]
If your language is either: English, German, Turkish, Dutch, Ukrainian or Russian. You can simply go to config.yml and change the "language:" property to the language you want and restart the server.

If not, you can already customize the language and config files: stop the server, then modify the language/config file, lastly restart the server.

**Comment by Clickism** [comment]
I will add multi language support in a future update.

**Comment by Clickism** [comment]
Added in the rewrite
