### ISSUE TITLE
Plugin not working on 1.20.1 Paper server

### ISSUE THREAD

**Issue by JusteRoro** [Clickism/ClickShop#5]
I installed the plugin, and restarted the server.
When I type in `/plugins`, the `ClickVillager` plugin shows up green, meaning it should be on and running.

However, when I left-click (or right-click, for that matter) the chest with a sign in hand, nothing happens.

Am I doing something wrong or is that a bug?

PS : I am the server admin, so it's not a permission issue.

**Comment by Clickism** [comment]
Are you sure you installed the right plugin? ClickVillagers is a utility plugin for villagers.

**Comment by JusteRoro** [comment]
I got the file from this Modrinth Page, so I think I got the right one : https://modrinth.com/plugin/clickshop

It downloads a file called `ClickVillager-0.1.1.jar`

**Comment by JusteRoro** [comment]
It's absolutely fine, don't worry. This kind of thing happens sometimes.

I'll download it as soon as I can and let you know how it goes.

**Comment by JusteRoro** [comment]
I downloaded it on Spigot and it seems to work fine!

Thanks you.
