### ISSUE TITLE
Duping Items with non existing Items in Stockpile

### ISSUE THREAD

**Issue by JustSimplyGaming** [Clickism/ClickShop#6]
Hi,

I found a problem...
When the seller wanna sell 2 Stacks of an Item (1 iron for 128x Dias) and places only 64 Dias in the Stock of the Chest, then the buyer can still buy the two stacks. Thats incorrect, and a big Problem.

**Comment by JustSimplyGaming** [comment]
Hello? ^^' @Clickism

**Comment by Clickism** [comment]
Hey! I'm moving soon so I can't really focus on any personal projects since uni also started. I'll try to fix it whenever I can though.

**Comment by JustSimplyGaming** [comment]
That's sad, cause it's an extreme game destroying Bug :/

**Comment by Clickism** [comment]
Fixed in the rewrite
