### ISSUE TITLE
Light not destroy

### ISSUE THREAD

**Issue by Saturn1B** [Clickism/ClickShop#7]
When deleting a shop, either by breaking the chest or clicking delete shop in the gui, if we previously set it up to have a light, the light is not destroyed.
![2023-12-21_13 47 41](https://github.com/Clickism/ClickShop/assets/60229050/dd935aa3-ef86-4975-90ae-1d8e698e1cde)

**Comment by Clickism** [comment]
Fixed in the rewrite
