### ISSUE TITLE
Feature request: Allow setting a normal chest as an earning pile

### ISSUE THREAD

**Issue by ColormaticStudios** [Clickism/ClickShop#9]
I run a server that uses this plugin, and I would like to be able to set a chest as an earning pile because I don't want my earnings to go to my ender chest, and I want to automate what is done with the earnings. Currently I am unable to do that.

**Comment by Clickism** [comment]
This feature probably won't be added since it seems pretty niche. Feel free to fork the project and try to implement it yourself though!
